"""add responsibility for object

Revision ID: 57563ccdd922
Revises: b1e8beb0cd76
Create Date: 2026-05-18 08:25:23.040641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57563ccdd922'
down_revision: Union[str, None] = 'b1e8beb0cd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_to_user', sa.Column('is_responsible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_to_user', 'is_responsible')
    # ### end Alembic commands ###
