"""create objects tables

Revision ID: 780ae254e7d4
Revises: bdbc9b976214
Create Date: 2026-05-13 04:40:19.419929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780ae254e7d4'
down_revision: Union[str, None] = 'bdbc9b976214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_table('object_to_foreman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('foreman_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foreman_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'foreman_id', name='uq_object_foreman')
    )
    op.create_index(op.f('ix_object_to_foreman_id'), 'object_to_foreman', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_to_foreman_id'), table_name='object_to_foreman')
    op.drop_table('object_to_foreman')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###
