"""delete object description

Revision ID: 9a5621fe8f05
Revises: 3c2d1e0f4a5b
Create Date: 2026-05-25 10:57:25.518170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5621fe8f05'
down_revision: Union[str, None] = '3c2d1e0f4a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
