"""allow chief engineers to be assigned to the object

Revision ID: b1e8beb0cd76
Revises: 780ae254e7d4
Create Date: 2026-05-18 08:23:47.031592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e8beb0cd76'
down_revision: Union[str, None] = '780ae254e7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_to_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'user_id', name='uq_object_user')
    )
    op.create_index(op.f('ix_object_to_user_id'), 'object_to_user', ['id'], unique=False)
    op.drop_index('ix_object_to_foreman_id', table_name='object_to_foreman')
    op.drop_table('object_to_foreman')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_to_foreman',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('foreman_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['foreman_id'], ['users.id'], name='object_to_foreman_foreman_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name='object_to_foreman_object_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='object_to_foreman_pkey'),
    sa.UniqueConstraint('object_id', 'foreman_id', name='uq_object_foreman')
    )
    op.create_index('ix_object_to_foreman_id', 'object_to_foreman', ['id'], unique=False)
    op.drop_index(op.f('ix_object_to_user_id'), table_name='object_to_user')
    op.drop_table('object_to_user')
    # ### end Alembic commands ###
