"""make notification read receipts for everyone

Revision ID: c20311dd0b84
Revises: 011a4a493542
Create Date: 2026-06-15 12:53:37.195133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20311dd0b84'
down_revision: Union[str, None] = '011a4a493542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_reads_notification_id')
    )
    op.create_index(op.f('ix_notification_reads_id'), 'notification_reads', ['id'], unique=False)
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notification_reads_id'), table_name='notification_reads')
    op.drop_table('notification_reads')
    # ### end Alembic commands ###
