"""add notification types

Revision ID: cbaa95f2d0ba
Revises: c20311dd0b84
Create Date: 2026-06-15 13:35:02.627540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbaa95f2d0ba'
down_revision: Union[str, None] = 'c20311dd0b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notifications',
        sa.Column(
            'type',
            sa.String(length=50),
            server_default='task_status_changed',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
